using VaultLib.Core.Types;

namespace VaultLib.Frameworks.Speed.Csis
{
    [VLTTypeInfo("Csis::Type_car_type")]
    public enum Type_car_type
    {
        Invalid_Type_car_type = 0x0,
        Type_car_type_McLaren = 0x1,
        Type_car_type_Porsche = 0x2,
        Type_car_type_FordGT = 0x4,
        Type_car_type_Viper = 0x8,
        Type_car_type_AstonMartin = 0x10,
        //Type_car_type_Lotus = 0x0,
        Type_car_type_Corvette = 0x20,
        Type_car_type_BMW = 0x40,
        Type_car_type_Mercedes = 0x80,
        Type_car_type_Audi = 0x100,
        Type_car_type_Mitsubishi = 0x200,
        Type_car_type_Mustang = 0x400,
        //Type_car_type_Cobalt = 0x0,
        Type_car_type_Challenger = 0x800,
        //Type_car_type_Chrysler = 0x0,
        Type_car_type_Camaro = 0x1000,
        Type_car_type_GTO || Type_car_type_Pontiac = 0x2000,
        //Type_car_type_Mini = 0x0,
        Type_car_type_Nissan = 0x4000,
        //Type_car_type_Opel = 0x0,
        Type_car_type_Mazda = 0x8000,
        Type_car_type_Lexus = 0x10000,
        //Type_car_type_Renault = 0x0,
        Type_car_type_Bugatti || Type_car_type_Veyron = 0x20000,
        Type_car_type_Volkswagen = 0x40000,
        Type_car_type_Koenigsegg || Type_car_type_CCX = 0x80000,
        Type_car_type_Charger = 0x100000,
        Type_car_type_Pagani = 0x200000,
        Type_car_type_Lamborghini = 0x400000,
        Type_car_type_Shelby = 0x800000,
        Type_car_type_Chevelle = 0x1000000,
        Type_car_type_SportsCar = 0x2000000,
        //Type_car_type_Sedan = 0x0,
        //Type_car_type_Pickup = 0x0,
        Type_car_type_Supra || Type_car_type_Toyota = 0x4000000,
        //Type_car_type_Subaru = 0x0,
        Type_car_type_Cadillac = 0x8000000,
        Type_car_type_Cuda || Type_car_type_Plymouth = 0x10000000,
        Type_car_type_Escort = 0x20000000,
        Type_car_type_Focus = 0x40000000,
    }
}
