using CoreLibraries.IO;
using System.Collections.Generic;
using System.IO;
using VaultLib.Core.DataInterfaces;
using VaultLib.Core.Hashing;

namespace VaultLib.Core.Chunks;

public class BinStringsChunk<TKey> : ChunkBase<TKey> where TKey : struct, IKey<TKey>
{
    public List<string> Strings { get; set; }

    public override uint Id => 0x53747245;
    public override uint Size { get; set; }
    public override long Offset { get; set; }

    public override void Read(VaultReadContext<TKey> context, BinaryReader br)
    {
        while (br.BaseStream.Position < EndOffset)
        {
            var offset = br.BaseStream.Position;
            string str = NullTerminatedString.Read(br);
            HashManager.AddVlt(str);
            context.Strings.Add(offset, str);
        }
    }

    public override void Write(VaultWriteContext<TKey> context, BinaryWriter bw)
    {
        // Assembly currentAssembly = Assembly.GetAssembly(typeof(Database));
        // AssemblyMetadataAttribute metadataAttribute =
        //     currentAssembly.GetCustomAttributes<AssemblyMetadataAttribute>().First(m => m.Key == "GitHash");
        //
        // Strings.Insert(0, "Generated by VaultBoy by heyitsleo");
        // Strings.Insert(1, $"{metadataAttribute.Value} | {DateTime.Now:s}");

        foreach (string s in Strings)
        {
            context.StringOffsets[s] = bw.BaseStream.Position;
            NullTerminatedString.Write(bw, s);
        }

        bw.AlignWriter(0x10);
    }
}