<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>heyitsleo/NFSTools</Authors>
    <Company>NFSTools</Company>
    <Description>Core library for processing VLT files - requires supplemental game modules</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>VaultLib.Core</PackageId>
    <Product>VaultLib.Core</Product>
    <TargetFramework>net9.0</TargetFramework>
    <Version>3.0.0-dev</Version>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSBuildGitHash" Version="0.5.0" />
    <PackageReference Include="NFSTools.Core.IO" Version="2.0.0" />
    <PackageReference Include="NFSTools.Core.ModuleSystem" Version="2.0.0" />
  </ItemGroup>

</Project>
