<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>heyitsleo/NFSTools</Authors>
    <Company>NFSTools</Company>
    <Description>Implements the modern AttribSys format</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>VaultLib.ModernBase</PackageId>
    <Product>VaultLib.ModernBase</Product>
    <TargetFramework>net6.0</TargetFramework>
    <Version>2.0.0-dev</Version>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VaultLib.Core\VaultLib.Core.csproj" />
  </ItemGroup>

</Project>
