namespace VaultLib.Support.MostWanted.VLT
{
    public enum eFEPartUpgradeLevels
    {
        PART_UPGRADE_EXOTIC_LEVEL_01 = 0x0,
        PART_UPGRADE_EXOTIC_LEVEL_02 = 0x1,
        PART_UPGRADE_EXOTIC_LEVEL_03 = 0x2,
        PART_UPGRADE_EXOTIC_LEVEL_04 = 0x3,
        PART_UPGRADE_EXOTIC_LEVEL_05 = 0x4,
        PART_UPGRADE_EXOTIC_LEVEL_06 = 0x5,
        PART_UPGRADE_EXOTIC_LEVEL_07 = 0x6,
        PART_UPGRADE_EXOTIC_LEVEL_08 = 0x7,
        PART_UPGRADE_EXOTIC_LEVEL_09 = 0x8,
        PART_UPGRADE_MUSCLE_LEVEL_01 = 0x9,
        PART_UPGRADE_MUSCLE_LEVEL_02 = 0xA,
        PART_UPGRADE_MUSCLE_LEVEL_03 = 0xB,
        PART_UPGRADE_MUSCLE_LEVEL_04 = 0xC,
        PART_UPGRADE_MUSCLE_LEVEL_05 = 0xD,
        PART_UPGRADE_MUSCLE_LEVEL_06 = 0xE,
        PART_UPGRADE_MUSCLE_LEVEL_07 = 0xF,
        PART_UPGRADE_MUSCLE_LEVEL_08 = 0x10,
        PART_UPGRADE_MUSCLE_LEVEL_09 = 0x11,
        PART_UPGRADE_TUNER_LEVEL_01 = 0x12,
        PART_UPGRADE_TUNER_LEVEL_02 = 0x13,
        PART_UPGRADE_TUNER_LEVEL_03 = 0x14,
        PART_UPGRADE_TUNER_LEVEL_04 = 0x15,
        PART_UPGRADE_TUNER_LEVEL_05 = 0x16,
        PART_UPGRADE_TUNER_LEVEL_06 = 0x17,
        PART_UPGRADE_TUNER_LEVEL_07 = 0x18,
        PART_UPGRADE_TUNER_LEVEL_08 = 0x19,
        PART_UPGRADE_TUNER_LEVEL_09 = 0x1A,
        NUM_PART_UPGRADE_LEVELS = 0x1B,
    }
}