<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>heyitsleo/NFSTools</Authors>
    <Company>NFSTools</Company>
    <Description>Support for Need for Speed: Most Wanted</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>VaultLib.Support.MostWanted</PackageId>
    <Product>VaultLib.Support.MostWanted</Product>
    <TargetFramework>net9.0</TargetFramework>
    <Version>3.0.0-dev</Version>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NFSTools.Core.ModuleSystem" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VaultLib.Frameworks.Speed\VaultLib.Frameworks.Speed.csproj" />
    <ProjectReference Include="..\VaultLib.LegacyBase\VaultLib.LegacyBase.csproj" />
  </ItemGroup>

</Project>
