namespace VaultLib.Support.Undercover.VLT
{
    public enum PresetRideAutosculptRegion
    {
        RegionFrontBumper = 0x0,
        RegionRearBumper = 0x1,
        RegionSkirtLeft = 0x2,
        RegionSkirtRight = 0x3,
        RegionRimsFront = 0x4,
        RegionRimsRear = 0x5,
        RegionDoorLeft = 0x6,
        RegionDoorRight = 0x7,
        RegionDoorRearLeft = 0x8,
        RegionDoorRearRight = 0x9,
        RegionFenderFrontLeft = 0xA,
        RegionFenderFrontRight = 0xB,
        RegionHoods = 0xC,
        RegionSpoilers = 0xD,
        RegionRoofScoops = 0xE,
        RegionRoofHeight = 0xF,
        RegionExhaust = 0x10,
        RegionFrontWindow = 0x11,
        RegionRearWindow = 0x12,
        RegionFrontLeftWindow = 0x13,
        RegionFrontRightWindow = 0x14,
        RegionRearLeftWindow = 0x15,
        RegionRearRightWindow = 0x16,
        RegionLeftDoor = 0x17,
        RegionRightDoor = 0x18,
        RegionInterior = 0x19,
        RegionDoorline = 0x1A,
        RegionDamageFront = 0x1B,
        RegionDamageRear = 0x1C,
        RegionWindTunnelType1 = 0x1D,
        RegionWindTunnelType2 = 0x1E,
        RegionWindTunnelType3 = 0x1F,
        RegionWindTunnelType4 = 0x20,
        RegionWindTunnelType5 = 0x21,
        RegionWindTunnelType6 = 0x22,
        RegionWindTunnelType7 = 0x23,
        RegionWindTunnelType8 = 0x24,
        RegionWindTunnelType9 = 0x25,
        RegionWindTunnelType10 = 0x26,
        RegionRearBumperExtra = 0x27,
        RegionNum = 0x28,
        RegionStart = 0x0,
        RegionEnd = 0x28,
        RegionWindTunnelStart = 0x1D,
        RegionWindTunnelEnd = 0x26,
        RegionDamageStart = 0x1B,
        RegionDamageEnd = 0x1C,
        RegionDamageNum = 0x2,
        RegionPresetRideLast = 0x10,
        RegionInvalid = 0x11,
    }
}